name: 'Autopuppeteer'
description: 'Automatically puppeteer a webbrowser to accomplish a given task'
inputs:
  goal:
    required: true
  url:
    required: true
  openai_api_token:
    required: true
  username:
    default: ''
  password:
    default: ''
  cookie:
    default: ''
outputs:
  result:
runs:
  using: composite
  steps:
    - name: "Install dependencies"
      shell: bash
      run: DEBIAN_FRONTEND=noninteractive apt-get -y install sed grep jq curl xvfb libx11-xcb1 libxcomposite1 libasound2t64 libatk1.0-0 libatk-bridge2.0-0 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 libnss3
    - name: "Setup node"
      uses: actions/setup-node@v6.1.0
      with:
        node-version: 24
    - name: "Install puppeteer"
      shell: bash
      run: npm install
    - name: "Setup X server
      shell: bash
      run: [ -n "${DISPLAY:-}" ] || (Xvfb :99 -screen 0 1280x1024x24 >&2 & sleep 5 && echo DISPLAY=:99 >> "$GITHUB_ENV")
    - name: "DANCE FOR ME"
      shell: bash
      run: bash ${{ github.action_path }}/puppeteer.sh | xargs -0 -I '{}' printf 'result=%s\n' '{}' >> "$GITHOUT_OUTPUT"
      env:
        GOAL: ${{ inputs.goal }}
        URL: ${{ inputs.url }}
        OPENAI_API_TOKEN: ${{ inputs.openai_api_token }}
        USERNAME: ${{ inputs.username }}
        PASSWORD: ${{ inputs.password }}
        COOKIE: ${{ inputs.cookie }}
