name: CI

on:
  push:
    branches: main
    paths:
      - 'VERSION'

jobs:

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      models: read
      actions: read
    steps:
      - uses: actions/checkout@v6
      - id: autopuppeteer
        uses: ./
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          goal: find the date the english wiki page about giraffes has been last modified
          url: https://www.wikipedia.org/
          openai_api_token: ${{ secrets.OPENAI_TOKEN }}
          debug: 1
      - run: |
          echo ::notice::"${{ steps.autopuppeteer.outputs.result }}"
          echo ::notice::"$(cat ${{ steps.autopuppeteer.outputs.result_path }})"
      - run: |
          [ "${{ steps.autopuppeteer.outputs.result }}" = "$(cat ${{ steps.autopuppeteer.outputs.result_path }})" ]
      - run: |
          day="$(cat ${{ steps.autopuppeteer.outputs.result_path }} | cut -d ' ' -f 1)"
          [ "$day" -ge 1 ] && [ "$day" -le 31 ] || exit 1
      - run: |
          month="$(cat ${{ steps.autopuppeteer.outputs.result_path }} | cut -d ' ' -f 2)"
          case "$month" in
            January|February|March|April|May|June|July|August|September|October|November|December) :;;
            *) exit 1;;
          esac
      - run: |
          year="$(cat ${{ steps.autopuppeteer.outputs.result_path }} | cut -d ' ' -f 3)"
          [ "$year" -ge 2026 ] && [ "$year" -le "$(date +%Y)" ] || exit 1

  release:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@v5.49.0
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
        with:
          secrets_to_redact: ${{ github.token }}
      - uses: actions/checkout@v6
      - run: |
          GH_TOKEN=${{ github.token }} release create v"$(cat VERSION)" --title v"$(cat VERSION)" --target ${{ github.sha }} --generate-notes
